language: r
cache: packages
env:
  global:
  - secure: JrbjoW10z71kw0TI8Qb/ZI4703ZPTa6QiuJjZ1BQYoSJzDS5DBuAVy+pKS6KzAG/Zm5PdIrrdYOsrvIzcPt1pcyeng6lIcDeATvMgRBIWccyP9ITeMOIpF0n/y1ohvly50xk8ddt9+LiAIM37SvEXStIdjdlrOn/ooZMVY54QqCanms10aNiEQn7RSaBIu0wPOVEKcTQmtGzSdIPpYVZvn52kHAUDzQqbQHFOzGWWkxKkP6534xv0xqbQfMm0GZiOyRVOEVxnL5zPs/LusPgJrdaKyH40SHlVmJ8IDUNz5hitM0yvefRBJgA1E0rpAWvEYJqEK2JYud1YsJP4i1Mb5NywvsO8T4YyZakmII1r7083subjUKP0mrJ/PBU7N53x1XSv39BsCvLvIK+RDIpYFQBzY/7W9rcAsj/9112L0fIHr+aEAovosQOhe1i3m+wrYzKFZpvS3X/vUFmZdWT/5/bWg8l1lyNtkaMx8nBiSbSg3/4cadyL+13VNkbMPl3ZarJ/yn8DfvDXwEhOf/ZmK+kzA5qlBoTf6Yi9R9PkpIzSW1niKVCZiJJL0UOvJrJrmkJ0jynZode+gXAAaNZgWuAbLWul40WtU1f2G5//1OT9DHSqv6S27ugMfSbkYghuZoEWWS6xcd3JycWhj3PtHlzUMMJf6aL1wCJJ5IdkF8=
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
- "./_deploy.sh"
dd:
  
